"""`loci chains render` -- generate docs/CHAINS.md.

GENERATED, never hand-edited, and the file says so in its first line. The
hand-edited artefact is `src/loci/chains/watchlist.yaml`; this document is that
file joined to the newest detect snapshot and to the press queue.

The join is deliberately a LEFT JOIN from the watchlist, and where the two
disagree the document PRINTS BOTH. Curated `nyc_locations_now` = 12 and
detected `locations_total` = 4 is not an error to be resolved silently -- it is
usually the franchisee-filing problem (docs/chains-process.md), and a reader who
cannot see the gap cannot tell a well-covered brand from a badly covered one.
"""
from __future__ import annotations

import datetime as dt
import math
import pathlib

from loci.chains import detect as detect_mod
from loci.chains import research as research_mod
from loci.chains import watchlist as wl

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
OUT_PATH = REPO_ROOT / "docs" / "CHAINS.md"

HEADER = """<!-- GENERATED BY `loci chains render` -- DO NOT EDIT BY HAND. -->
<!-- The hand-edited source of truth is src/loci/chains/watchlist.yaml.     -->
<!-- Regenerate with: make chains-refresh                                   -->
"""


def _fmt(value, dash: str = "—") -> str:
    if value is None or value == "":
        return dash
    if isinstance(value, float) and math.isnan(value):
        return dash
    return str(value)


def assemble(con, *, doc: dict | None = None, month: str | None = None) -> dict:
    """The one data pull shared by docs/CHAINS.md and the html page.

    Everything downstream (the markdown render, `render_html.build_data`) reads
    off this dict rather than re-querying `chains.brand_snapshot` or
    re-deriving the hand/auto/rejected split -- two independent
    implementations of "what counts as auto-admitted" is exactly how the two
    documents would quietly disagree."""
    doc = doc if doc is not None else wl.load()
    rows = list(doc.get("brands") or [])
    month = month or detect_mod.latest_month(con)

    snap: dict[str, dict] = {}
    if month:
        for r in con.execute(
                "SELECT * FROM chains.brand_snapshot WHERE snapshot_month = ?",
                [month]).fetchdf().to_dict("records"):
            snap[r["brand_key"]] = r

    pipe = _pipeline_counts(con, rows)
    rejected = [r for r in rows if wl.tier_of(r) == "rejected"]
    live = [r for r in rows if wl.tier_of(r) != "rejected"]
    hand = [r for r in live if not wl.is_auto(r)]
    auto = [r for r in live if wl.is_auto(r)]
    return {"doc": doc, "rows": rows, "month": month, "snap": snap, "pipe": pipe,
            "rejected": rejected, "live": live, "hand": hand, "auto": auto}


def render(con, *, doc: dict | None = None, month: str | None = None,
           top_detected: int = 40, today: dt.date | None = None) -> str:
    today = today or dt.date.today()
    asm = assemble(con, doc=doc, month=month)
    doc, rows, month, snap = asm["doc"], asm["rows"], asm["month"], asm["snap"]

    out: list[str] = [HEADER, "# NYC chains to watch", ""]
    n_auto = len(asm["auto"])
    n_rejected = len(asm["rejected"])
    out.append(f"**Generated** {today.isoformat()} · "
               f"**detect snapshot** {_fmt(month)} · "
               f"**watchlist** {len(rows)} brands "
               f"({len(rows) - n_auto - n_rejected} hand-vetted, {n_auto} auto-admitted, "
               f"{n_rejected} rejected) · {len(snap)} detected brands.")
    out.append("")
    out.append("Two uses: companies to sell a site-selection product to, and — later — "
               "the \"brand X is opening nearby\" signal on a recommendation card. "
               "`loci_category` is the join key that will make the second possible; "
               "nothing consumes it yet.")
    out.append("")
    out.append("> **Read the caveats before quoting a number.** Curated counts are what a "
               "person checked; detected counts come from open data and are a FLOOR "
               "(franchisee filings, DOHMH lag, and brands no city dataset can see all "
               "push them down). Where the two disagree, both are printed. "
               "See [chains-process.md](chains-process.md).")
    out.append("")

    out += _watchlist_section(rows, snap, asm["pipe"])
    out += _newly_detected_section(con, month, snap, rows, top_detected)
    out += _press_section(con, today)
    out += _provenance_section(month, today)
    return "\n".join(out).rstrip() + "\n"


def _pipeline_counts(con, rows: list[dict]) -> dict[str, dict]:
    """{brand_key: pipeline row} for the watchlist brands, from
    analysis.storefront_pipeline.

    DEGRADES TO AN EMPTY DICT when the table has not been built. A missing
    optional column is not a reason to fail the monthly document build --
    every cell simply renders as a dash, and `loci storefront-pipeline build`
    is what fills them (it is in `make chains-refresh`, ahead of detect).
    """
    try:
        from loci.model import storefront_pipeline as sp
    except ImportError:                                     # pragma: no cover
        return {}
    keys = [r.get("brand_key") for r in rows if r.get("brand_key")]
    if not keys or not sp.has_pipeline_table(con):
        return {}
    frame = sp.brand_pipeline(con, brand_keys=keys)
    return {r["brand_key"]: r for r in frame.to_dict("records")}


def _pipe_cell(p) -> str:
    """"N in BK,MN, from YYYY-MM-DD" -- the count alone is not actionable;
    where and when is. `first_entry` arrives as a pandas Timestamp whose time
    half is always midnight and is noise in a document."""
    if not p:
        return "—"
    return f"{p['pipeline_rows']} in {p['boroughs'] or '?'}, from {str(p['first_entry'])[:10]}"


def _watchlist_section(rows: list[dict], snap: dict[str, dict],
                       pipe: dict[str, dict] | None = None) -> list[str]:
    """Hand-vetted rows first, then the machine's, then a count of the rejected.

    THE ORDERING IS THE POINT (owner ruling, 2026-09-15). The monthly job now
    admits every brand that clears the D109 predicate, so this document mixes
    rows a person checked with rows nobody has seen. Sorting them together
    would launder the second kind into the first: a reader scanning the table
    has no way to tell which is which, and the whole value of the hand-vetted
    half is that somebody looked. They get their own section, with the reason
    the machine admitted them printed in a column, so the row can be rejected
    on what it actually claims."""
    out = ["## Watchlist — ranked by net new locations in 12 months", ""]
    if not rows:
        return out + ["_The watchlist is empty._", ""]
    pipe = pipe or {}

    rejected = [r for r in rows if wl.tier_of(r) == "rejected"]
    live = [r for r in rows if wl.tier_of(r) != "rejected"]
    hand = [r for r in live if not wl.is_auto(r)]
    auto = [r for r in live if wl.is_auto(r)]

    def key(r):
        n = r.get("net_new_12m")
        return (0 if n is None else 1, n or 0)

    out += ["| Brand | Category | loci_category | Net new 12m (curated) | "
            "NYC now (curated) | Detected total | Detected new 12m | "
            "Pipeline (gov filings) | Confidence | Last verified |",
            "|---|---|---|---:|---:|---:|---:|---|---|---|"]
    for r in sorted(hand, key=key, reverse=True):
        bk = r.get("brand_key") or ""
        d = snap.get(bk, {})
        out.append("| {b} | {c} | {lc} | {nn} | {now} | {dt_} | {dn} | {pl} | "
                   "{conf} | {lv} |".format(
            b=_fmt(r.get("brand")), c=_fmt(r.get("category")),
            lc=_fmt(r.get("loci_category")), nn=_fmt(r.get("net_new_12m")),
            now=_fmt(r.get("nyc_locations_now")),
            dt_=_fmt(d.get("locations_total")), dn=_fmt(d.get("locations_new_12m")),
            pl=_pipe_cell(pipe.get(bk)),
            conf=_fmt(r.get("confidence")), lv=_fmt(r.get("last_verified"))))
    out.append("")
    if rejected:
        # Counted, never listed: the list is what a reader would act on, and a
        # rejected brand is precisely the one nobody should act on. The count
        # is here so "the watchlist is 161 brands" and "the file has 190 rows"
        # do not read as a discrepancy.
        out.append(f"_{len(rejected)} rejected row{'s' if len(rejected) != 1 else ''} "
                   "omitted from the table above and kept in `watchlist.yaml` so the "
                   "same brands are not re-surfaced every month. A rejection re-opens "
                   "automatically if the brand's location count doubles._")
        out.append("")
    out.append("`Pipeline (gov filings)` counts rows in `analysis.storefront_pipeline` "
               "that are filed under this brand's key and are **not yet open** — a "
               "lease signed, a build-out permitted or a licence applied for, with no "
               "regulator having seen a business yet. It is a FLOOR: a franchisee files "
               "under its own operating company (`PRIYA FOODS INC` running a Dunkin'), "
               "so an empty cell is as often \"files under another name\" as it is "
               "\"nothing coming\". A filing is also not a store — applications are "
               "withdrawn and permits lapse.")
    out.append("")

    out += _auto_section(auto, snap, pipe)

    unverified = [r for r in live if (r.get("confidence") or "unverified") == "unverified"]
    if unverified:
        out.append(f"_{len(unverified)} of {len(live)} rows are `unverified` — "
                   "seeded to exercise the pipeline, not checked. Do not quote them._")
        out.append("")

    detail = [r for r in live if (r.get("why_they_grow") or "").strip()]
    if detail:
        out += ["### Why they grow", ""]
        for r in sorted(detail, key=lambda x: (x.get("brand") or "").lower()):
            ev = r.get("evidence") or []
            cites = " ".join(f"[[{i + 1}]]({e.get('url')})" for i, e in enumerate(ev)
                             if isinstance(e, dict) and e.get("url"))
            role = r.get("expansion_role_title")
            bits = [" ".join((r.get("why_they_grow") or "").split())]
            if r.get("pipeline"):
                bits.append(f"Pipeline: {r['pipeline']}.")
            if role:
                bits.append(f"Site selection sits with: **{role}**.")
            out.append(f"- **{_fmt(r.get('brand'))}** — {' '.join(bits)} {cites}".rstrip())
        out.append("")
    return out


def _auto_section(auto: list[dict], snap: dict[str, dict],
                  pipe: dict[str, dict]) -> list[str]:
    """Rows the monthly job admitted on the predicate alone.

    Heading says what they are, because `confidence: auto` in a column is not a
    warning anybody reads. Sorted by the detected 12-month count, since that is
    the number that put them here -- curated `net_new_12m` is null on every one
    of them by construction."""
    if not auto:
        return []
    out = ["## Auto-admitted this snapshot (nobody has looked yet)", "",
           f"{len(auto)} brand{'s' if len(auto) != 1 else ''} admitted by "
           "`loci chains auto-admit` because they cleared the D109 candidate "
           "predicate and no exclusion rule fired. **Nobody has checked any of "
           "them.** `NYC now` is deliberately empty — the machine has a detect "
           "count, which is a floor off open data, and writing it into the "
           "curated column would manufacture a count nobody produced. Reject "
           "one with `loci chains reject <brand_key> --reason \"...\"`; "
           "promote one with `loci chains admit`.", ""]
    out += ["| Brand | loci_category | Detected total | Detected new 12m | "
            "Pipeline (gov filings) | Sales role | Admitted because | Decided on |",
            "|---|---|---:|---:|---|---|---|---|"]

    def key(r):
        bk = r.get("brand_key") or ""
        d = snap.get(bk, {})
        return (d.get("locations_new_12m") or 0, d.get("locations_total") or 0)

    for r in sorted(auto, key=key, reverse=True):
        bk = r.get("brand_key") or ""
        d = snap.get(bk, {})
        out.append("| {b} | {lc} | {dt_} | {dn} | {pl} | {role} | {why} | {on} |".format(
            b=_fmt(r.get("brand")), lc=_fmt(r.get("loci_category")),
            dt_=_fmt(d.get("locations_total")), dn=_fmt(d.get("locations_new_12m")),
            pl=_pipe_cell(pipe.get(bk)), role=_fmt(r.get("sales_role")),
            why=_fmt(r.get("admission_reason")), on=_fmt(r.get("decided_on"))))
    out.append("")
    return out


def _newly_detected_section(con, month, snap, rows, limit: int) -> list[str]:
    """Flagged brands that nobody has put on the watchlist. This is the section
    that earns the command: it is the candidate queue."""
    known = {r.get("brand_key") for r in rows}
    out = ["## Newly detected, not on the watchlist", ""]
    if not month:
        return out + ["_No detect snapshot yet — run `loci chains detect`._", ""]

    flagged = [r for r in detect_mod.flagged_brands(con, month)
               if r["brand_key"] not in known]
    if not flagged:
        return out + ["_Nothing flagged outside the watchlist in this snapshot._", ""]

    out.append(f"{len(flagged)} brands flagged by `loci chains detect` "
               f"({month}); the {min(limit, len(flagged))} fastest are listed. "
               "These are CANDIDATES, not findings — see the caveats.")
    out.append("")
    out += ["| Brand | loci_category | Locations | Dated | New 12m | New 3m | "
            "Boroughs | Sources | Why flagged |",
            "|---|---|---:|---:|---:|---:|---:|---:|---|"]
    for r in flagged[:limit]:
        out.append("| {b} | {c} | {t} | {d} | {n12} | {n3} | {nb} | {ns} | {why} |".format(
            b=_fmt(r.get("display_name") or r["brand_key"]),
            c=_fmt(r.get("loci_category")), t=r["locations_total"],
            d=r["locations_dated"], n12=r["locations_new_12m"],
            n3=r["locations_new_3m"], nb=r["n_boroughs"], ns=r["n_sources"],
            why=_fmt(r.get("flag_reason"))))
    out.append("")
    out.append("`Dated` is how many of that brand's locations carry a first-seen date at "
               "all. When `Dated` is much smaller than `Locations`, `New 12m` is a floor "
               "computed on a small subset and the ranking is weak evidence.")
    out.append("")
    return out


def _press_section(con, today: dt.date) -> list[str]:
    out = ["## Recent press", ""]
    try:
        hits = research_mod.recent_hits(con, today=today)
    except Exception:                    # noqa: BLE001 -- table may not exist yet
        hits = []
    if not hits:
        return out + ["_No press hits — run `loci chains research`._", ""]
    out.append(f"{len(hits)} hits in the last {research_mod.DEFAULT_DAYS} days. "
               "A hit is a headline, not evidence; promoting one to the watchlist "
               "is a human decision.")
    out.append("")
    out += ["| Date | Brand | Headline | Kind |", "|---|---|---|---|"]
    for h in hits:
        title = " ".join(str(h.get("title") or h["url"]).split())[:140]
        out.append(f"| {_fmt(h.get('published_on'))} | "
                   f"{_fmt(h.get('brand_key'), dash='(discovery)')} | "
                   f"[{title}]({h['url']}) | {_fmt(h.get('query_kind'))} |")
    out.append("")
    return out


def _provenance_section(month, today: dt.date) -> list[str]:
    aliases = detect_mod.alias_report()
    return [
        "## Provenance",
        "",
        f"- Detect snapshot: `chains.brand_snapshot` at `{_fmt(month)}`, built from "
        "`analysis.poi_supply` (deduped locations) with no supply-set filter.",
        f"- A brand needs ≥ {detect_mod.MIN_LOCATIONS} deduped locations to appear.",
        f"- Flag rule: ≥ {detect_mod.FLAG_NEW_12M} new locations in 12 months, OR "
        f"≥ {detect_mod.FLAG_FAST_SMALL_NEW} new with ≤ "
        f"{detect_mod.FLAG_FAST_SMALL_TOTAL} total.",
        f"- Manual brand collapses in force ({len(aliases)}): "
        + ", ".join(f"`{k}` → `{v}`" for k, v in sorted(aliases.items())) + ".",
        f"- Regenerated {today.isoformat()} by `loci chains render`.",
        "",
    ]


def write(text: str, path: pathlib.Path | None = None) -> pathlib.Path:
    target = path or OUT_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    return target
